server:
  port: 7001
  servlet:
    context-path: / #项目的上下文路径
spring:
  datasource:
    url: jdbc:mysql://139.196.59.66:3306/covid
    username: covid
    password: Wsxedc08-
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
    thymeleaf:
      cache: false

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml #加载映射文件
  type-aliases-package: com.zhd.domain #别名搜索的包
  configuration:
    lazy-loading-enabled: true #打开懒加载
    aggressive-lazy-loading: false #关闭积极懒加载

#HTTP
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

#comment
comment_server:
  host: ${HOST:139.196.59.66}
  port: ${PORT:7002}

#图片配置
picture:
  path: /root/covid_game/backend/
